### ISSUE TITLE
"dojo build theme" command does not generate any file.

### ISSUE THREAD

**Issue by sputnyq** [dojo/cli-build-theme#19]
**Bug** 
`dojo build theme` does not generate any file

Package Version: 5+

**Code**

Windows 10 x64 Enterprise

Example to reproduce can be found [here](https://github.com/nka089/theme-example)

**Expected behavior:**

Files to export and release a theme

**Actual behavior:**

only `dist/src/petrol` directories were generated

**Comment by mwistrand** [comment]
@nka089 I am so sorry for the delay in response; if you have created a theme within an existing application using `@dojo/cli-create-theme`, then `@dojo/cli-build-theme` is unnecessary (and, as you have discovered, will not work). It is unnecessary because the theme is baked into the app itself, can be imported by your widget files like any other TypeScript or CSS file, and will be included in `@dojo/cli-build-app`'s pipeline. It does not work because `@dojo/cli-build-theme` assumes you are building a standalone theme project with the directory structure: `src/{theme}/index.ts`, not `src/themes/{theme}/theme.ts`.

I am closing this issue, but please feel free to re-open it if you feel your concerns have not been addressed. Thanks!
